name: build

on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache-dependency-path: '**/go.sum'
      - run: ./goyek.sh -v all diff
      - name: Upload HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.*
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out

  compatibility:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.18'
          - '1.19'
          - '1.20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -race ./...
